# Generated by Django 3.2 on 2021-05-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210427_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bug_fixed',
            new_name='os',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bus_used',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='charisma',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='inteligence',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ios',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='money',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='obstinacy',
        ),
    ]
